# Generated by Django 5.0.1 on 2024-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='статус оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.TextField(blank=True, null=True, verbose_name='сессия'),
        ),
    ]
