# Generated by Django 5.0 on 2024-02-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default='2024-02-02', verbose_name='Последний вход'),
        ),
    ]
