# Generated by Django 5.0 on 2024-02-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='update',
            field=models.TextField(default='Новые материалы курса', verbose_name='обновление'),
        ),
    ]
