# Generated by Django 5.0 on 2024-02-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_lesson_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='update',
        ),
        migrations.AddField(
            model_name='course',
            name='update',
            field=models.BooleanField(default=True, verbose_name='обновление'),
        ),
    ]
